### ISSUE TITLE
Exception thrown at 0x00007FFD0445A3AF (opencv_world340d.dll) in fire-smoke detection.exe

### ISSUE THREAD

**Issue by sRahiimii** [hojak99/fire-detection#5]
Hi. I tried to run the solution but it had an exception. How can i handle this exception? Which part of the code has an exception? I cant figure it out.
Here is the exception:
"Exception thrown at 0x00007FFD0445A3AF (opencv_world340d.dll) in fire-smoke detection.exe: 0xC0000005: Access violation reading location 0x000001D0856A9000.

If there is a handler for this exception, the program may be safely continued."

**Comment by hojak99** [comment]
I used version 3.1.0 of opencv. but you used 3.4.0
